### ISSUE TITLE
Password prompt response can get cached

### ISSUE THREAD

**Issue by dpoirier** [Dunedan/django-lockdown#9] opened 2016-09-09 13:51 UTC
We recently enabled a caching engine on a site and starting having problems where lockdown's password prompt would keep getting displayed even after entering a valid password.  

I believe this was due to Django's caching middleware caching the response from lockdown.  

I'm working around it by putting the lockdown middleware just after the session middleware in MIDDLEWARE_CLASSES instead of at the end, but it would probably be better if the response headers when lockdown prompts for a password were to indicate that the response should never be cached.

**Comment by Dunedan** [comment] 2016-09-10 07:30
Thanks for reporting that issue. I'll try to have a look into it during the next days.

**Comment by Dunedan** [comment] 2016-09-11 13:17
Hi Dan,
I tried to reproduce the behavior with a clean Django project with activated [side-wide caching](https://docs.djangoproject.com/es/1.10/topics/cache/#the-per-site-cache) using Djangos caching middleware, but wasn't able to reproduce the behavior. Can you please add some details about your setup, which might help to reproduce this issue?

**Comment by Dunedan** [comment] 2016-09-24 05:30
Hi Dan,
anything new regarding the problem? It'd be really great if you could provide some additional information about the environment as I'm not able to reproduce it.

**Comment by dpoirier** [comment] 2016-09-28 14:49
Have you tried putting the django-lockdown middleware at the end of MIDDLEWARE_CLASSES, where we had it?  We haven't seen the problem since moving it to immediately after the session middleware, before the cache fetch middleware.

**Comment by Dunedan** [comment] 2016-10-25 07:34
I just tried it once again with the `lockdown.middleware.LockdownMiddleware` after `django.middleware.cache.FetchFromCacheMiddleware`, but I'm still unable to reproduce this problem.
Also please mind that no other middleware should be placed after the `django.middleware.cache.FetchFromCacheMiddleware` anyway:

> No, that’s not a typo: the “update” middleware must be first in the list, and the “fetch” middleware must be last. The details are a bit obscure, but see Order of MIDDLEWARE below if you’d like the full story.

https://docs.djangoproject.com/en/1.10/topics/cache/#the-per-site-cache

If you can provide me with a reliable way to reproduce the problem, I'm glad to look for a solution, otherwise I'll have to close this issue, as I simply can't reproduce it.

**Comment by dpoirier** [comment] 2016-10-31 11:28
Sorry, I have not had time to try to reproduce it locally. After
rearranging our own middleware settings, we haven't seen it again anyway.

_Dan Poirier_Django Developer

dpoirier@caktusgroup.com
www.caktusgroup.com

**Comment by Dunedan** [comment] 2016-10-31 20:56
Closed as not reproducible for now. If somebody is able to reproduce it, I'm happy to re-open this issue again.

**Closed as completed by Dunedan** 2016-10-31 20:56 UTC
Labels: bug
